ladies = Category.create(name:"レディース")
ladies_tops = ladies.children.create(name:"トップス")
ladies_juckets = ladies.children.create(name:"ジャケット/アウター")
ladies_tops.children.create([{name:"Tシャツ/カットソー(半袖/袖なし)"}, {name:"Tシャツ/カットソー(七分/長袖)"}, {name:"シャツ/ブラウス(半袖/袖なし)"}, {name:"シャツ/ブラウス(七分/長袖)"}, {name:"ポロシャツ"}, {name:"キャミソール"}, {name:"タンクトップ"}, {name:"ホルターネック"}, {name:"ニット/セーター"}, {name:"チュニック"}, {name:"カーディガン/ボレロ"}, {name:"アンサンブル"}, {name:"ベスト/ジレ"}, {name:"パーカー"}])
ladies_juckets.children.create([{name:"テーラードジャケット"}, {name:"ノーカラージャケット"}, {name:"Gジャン/デニムジャケット"}, {name:"レザージャケット"}, {name:"ダウンジャケット"}, {name:"ライダースジャケット"}, {name:"ミリタリージャケット"}, {name:"ダウンベスト"}, {name:"ジャンパー/ブルゾン"}, {name:"ポンチョ"}, {name:"ロングコート"}, {name:"トレンチコート"}, {name:"ダッフルコート"}, {name:"ピーコート"}])